/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Formation
 */
public class PrincipaleVue extends javax.swing.JFrame {

    /**
     * Creates new form PrincipaleVue
     */
    public PrincipaleVue() {
        initComponents();
    }

    public JMenuItem getListeCommandes() {
        return ListeCommandes;
    }

    public void setListeCommandes(JMenuItem ListeCommandes) {
        this.ListeCommandes = ListeCommandes;
    }

    public JMenuItem getListeProduits() {
        return ListeProduits;
    }

    public void setListeProduits(JMenuItem ListeProduits) {
        this.ListeProduits = ListeProduits;
    }

    public JMenuItem getMenuCat() {
        return MenuCat;
    }

    public void setMenuCat(JMenuItem MenuCat) {
        this.MenuCat = MenuCat;
    }

    public JMenu getMenuCommande() {
        return MenuCmd;
    }

    public void setMenuCommande(JMenu MenuCommande) {
        this.MenuCmd = MenuCommande;
    }

    public JMenuItem getMenuProd() {
        return MenuProd;
    }

    public void setMenuProd(JMenuItem MenuProd) {
        this.MenuProd = MenuProd;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu10() {
        return jMenu10;
    }

    public void setjMenu10(JMenu jMenu10) {
        this.jMenu10 = jMenu10;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenu getjMenu4() {
        return jMenu4;
    }

    public void setjMenu4(JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    public JMenu getMenuCmd() {
        return MenuCmd;
    }

    public void setMenuCmd(JMenu MenuCmd) {
        this.MenuCmd = MenuCmd;
    }

    public JMenuItem getMenuCommandes2() {
        return MenuCommandes2;
    }

    public void setMenuCommandes2(JMenuItem MenuCommandes2) {
        this.MenuCommandes2 = MenuCommandes2;
    }

    public JMenu getjMenu5() {
        return jMenu5;
    }

    public void setjMenu5(JMenu jMenu5) {
        this.jMenu5 = jMenu5;
    }

    public JMenu getjMenu6() {
        return jMenu6;
    }

    public void setjMenu6(JMenu jMenu6) {
        this.jMenu6 = jMenu6;
    }

    public JMenu getjMenu7() {
        return jMenu7;
    }

    public void setjMenu7(JMenu jMenu7) {
        this.jMenu7 = jMenu7;
    }

    public JMenu getjMenu8() {
        return jMenu8;
    }

    public void setjMenu8(JMenu jMenu8) {
        this.jMenu8 = jMenu8;
    }

    public JMenu getjMenu9() {
        return jMenu9;
    }

    public void setjMenu9(JMenu jMenu9) {
        this.jMenu9 = jMenu9;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JMenuItem getjMenuItem2() {
        return jMenuItem2;
    }

    public void setjMenuItem2(JMenuItem jMenuItem2) {
        this.jMenuItem2 = jMenuItem2;
    }

    public JMenuItem getjMenuItem3() {
        return MenuCommandes2;
    }

    public void setjMenuItem3(JMenuItem jMenuItem3) {
        this.MenuCommandes2 = jMenuItem3;
    }

    public JCheckBoxMenuItem getListeCat() {
        return listeCat;
    }

    public void setListeCat(JCheckBoxMenuItem listeCat) {
        this.listeCat = listeCat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        MenuCat = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        MenuProd = new javax.swing.JMenuItem();
        MenuCmd = new javax.swing.JMenu();
        MenuCommandes2 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        listeCat = new javax.swing.JCheckBoxMenuItem();
        ListeProduits = new javax.swing.JMenuItem();
        ListeCommandes = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenuItem2.setText("jMenuItem2");

        jMenu9.setText("jMenu9");

        jMenu8.setText("jMenu8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DE STOCK");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Catégories");

        MenuCat.setText("Gestion catégorie");
        jMenu4.add(MenuCat);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Produits");

        MenuProd.setText("Gestion Produits");
        jMenu7.add(MenuProd);

        jMenuBar1.add(jMenu7);

        MenuCmd.setText("Commandes");

        MenuCommandes2.setText("Gestion des commandes");
        MenuCmd.add(MenuCommandes2);

        jMenuBar1.add(MenuCmd);

        jMenu10.setText("Etats");

        listeCat.setSelected(true);
        listeCat.setText("liste catégorie");
        jMenu10.add(listeCat);

        ListeProduits.setText("Liste produits");
        jMenu10.add(ListeProduits);

        ListeCommandes.setText("Liste des commandes");
        jMenu10.add(ListeCommandes);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipaleVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipaleVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipaleVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipaleVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipaleVue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListeCommandes;
    private javax.swing.JMenuItem ListeProduits;
    private javax.swing.JMenuItem MenuCat;
    private javax.swing.JMenu MenuCmd;
    private javax.swing.JMenuItem MenuCommandes2;
    private javax.swing.JMenuItem MenuProd;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JCheckBoxMenuItem listeCat;
    // End of variables declaration//GEN-END:variables
}
